services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      - DB_HOST=notification_db
    ports:
      - "8000:8000"
    networks:
      - laravel
    command: /usr/local/bin/entrypoint.sh  # Запуск скрипта при старте контейнера

  db:
    image: mysql:8
    container_name: notification_db
    restart: always
    environment:
      MYSQL_DATABASE: notification_service
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge